(()=>{
const {state,done,$,sheetUrl}=BJT;
const lessons=id=>state.lessons.filter(x=>x.book_id===id).sort((a,b)=>(+a.sort_order||0)-(+b.sort_order||0));
function books(){const q=state.query.toLowerCase();$('bookList').innerHTML=state.books.filter(b=>!q||String(b.book_title).toLowerCase().includes(q)||lessons(b.book_id).some(l=>(l.part_title+' '+l.section_title).toLowerCase().includes(q))).map(b=>{const ls=lessons(b.book_id),n=ls.filter(l=>done.has(l.lesson_id)).length,p=ls.length?Math.round(n/ls.length*100):0;return`<button class="book-btn ${b.book_id===state.bookId?'active':''}" data-id="${b.book_id}"><strong>${b.book_title}</strong><small>${b.pages||'?'} trang · ${ls.length} bài · ${n} đã học</small><div class="book-progress"><div style="width:${p}%"></div></div></button>`}).join('');document.querySelectorAll('.book-btn').forEach(x=>x.onclick=()=>{state.bookId=x.dataset.id;state.lessonId='';localStorage.setItem('bjtLastBook',state.bookId);render()})}
function lessonMenu(){const b=state.books.find(x=>x.book_id===state.bookId);if(!b)return;let ls=lessons(b.book_id);if(state.query){const q=state.query.toLowerCase();ls=ls.filter(l=>(l.part_title+' '+l.section_title).toLowerCase().includes(q))}$('bookTitle').textContent=b.book_title;$('bookInfo').textContent=`${b.pages||'?'} trang · ${b.data_status==='structured'?'đã chia theo phần thi':'chia theo nhóm trang từ PDF'}`;$('bookBadge').textContent=b.data_status==='structured'?'BJT 100 câu':'PDF giáo trình';const groups=ls.reduce((a,x)=>((a[x.part_title||b.book_title]??=[]).push(x),a),{});$('lessonGroups').innerHTML=ls.length?Object.entries(groups).map(([g,a])=>`<section class="lesson-group"><div class="group-head"><strong>${g}</strong><span>${a.length} bài</span></div><div class="lesson-list">${a.map((l,i)=>`<button class="lesson-card ${l.lesson_id===state.lessonId?'active':''} ${done.has(l.lesson_id)?'done':''}" data-id="${l.lesson_id}"><div class="top"><span>${done.has(l.lesson_id)?'✓':String(i+1).padStart(2,'0')}</span><span>tr. ${l.page_start}-${l.page_end}</span></div><strong>${l.section_title}</strong><small>${+l.item_count?l.item_count+' câu':'Mở PDF nguồn'}</small></button>`).join('')}</div></section>`).join(''):'<div class="empty">Không tìm thấy bài.</div>';document.querySelectorAll('.lesson-card').forEach(x=>x.onclick=()=>{state.lessonId=x.dataset.id;localStorage.setItem('bjtLastLesson',state.lessonId);render()});if(!state.lessonId&&ls.length){state.lessonId=ls[0].lesson_id;localStorage.setItem('bjtLastLesson',state.lessonId)}}
const norm=s=>String(s||'').replace(/^Phần \d+\s*-\s*/,'').replace(/^Section \d+\s*-\s*/,'').trim();
function detail(){const l=state.lessons.find(x=>x.lesson_id===state.lessonId),b=state.books.find(x=>x.book_id===state.bookId);if(!l||!b){$('lessonDetail').innerHTML='<div class="empty">Chọn một bài trong menu.</div>';return}const qs=state.questions.filter(q=>q.book_id===l.book_id&&norm(q.part_title)===norm(l.part_title)&&norm(q.section_title)===norm(l.section_title));$('lessonStatus').textContent=done.has(l.lesson_id)?'Đã hoàn thành':'Đang học';$('lessonDetail').className='detail';$('lessonDetail').innerHTML=`<div class="detail-main"><p class="eyebrow">${l.part_title}</p><h3>${l.section_title}</h3><p>Học trong PDF nguồn từ trang ${l.page_start} đến ${l.page_end}. ${+l.item_count?`Phần này có ${l.item_count} câu hỏi.`:'Đây là một nhóm trang của giáo trình.'}</p><div class="detail-meta"><span class="meta">Trang ${l.page_start}-${l.page_end}</span><span class="meta">Google Drive</span></div><div class="detail-actions"><button id="openPdf" class="action primary">Mở đúng trang PDF ↗</button><button id="toggleDone" class="action good">${done.has(l.lesson_id)?'Bỏ hoàn thành':'✓ Đánh dấu hoàn thành'}</button>${b.source_folder_url?'<button id="openFolder" class="action">Mở thư mục sách/audio</button>':''}<button id="openData" class="action">Mở bảng dữ liệu</button></div></div><aside class="detail-side"><h4>${qs.length?'Danh sách câu':'Hướng dẫn học'}</h4><p>${qs.length?'Chạm câu để mở đúng trang; dấu ♫ là câu có audio.':'Đọc tuần tự nhóm trang này rồi đánh dấu hoàn thành.'}</p><div class="question-list">${qs.length?qs.map(q=>`<button class="question-chip ${q.audio_track?'has-audio':''}" data-page="${q.pdf_page}" title="${q.audio_track||''}">Q${q.question_no}</button>`).join(''):'<span class="meta">Nội dung gốc nằm trong PDF</span>'}</div></aside>`;$('openPdf').onclick=()=>window.open(l.source_url||`${b.pdf_url}#page=${l.page_start}`,'_blank','noopener');$('toggleDone').onclick=()=>{done.has(l.lesson_id)?done.delete(l.lesson_id):done.add(l.lesson_id);localStorage.setItem('bjtDoneLessons',JSON.stringify([...done]));toast(done.has(l.lesson_id)?'Đã lưu hoàn thành':'Đã bỏ đánh dấu');render()};if($('openFolder'))$('openFolder').onclick=()=>window.open(b.source_folder_url,'_blank','noopener');$('openData').onclick=()=>window.open(sheetUrl,'_blank','noopener');document.querySelectorAll('.question-chip').forEach(x=>x.onclick=()=>window.open(`${b.pdf_url}#page=${x.dataset.page}`,'_blank','noopener'))}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1500)}
function render(){if(!state.books.some(x=>x.book_id===state.bookId))state.bookId=state.books[0]?.book_id||'';books();lessonMenu();detail();$('doneCount').textContent=done.size}
window.BJT_UI={render,toast};
})();