const BASIC_ROWS=[
{row:'Nguyên âm',items:[['a','あ','ア','a'],['i','い','イ','i'],['u','う','ウ','ư/u nhẹ'],['e','え','エ','ê'],['o','お','オ','ô']]},
{row:'Hàng K',items:[['ka','か','カ','ca'],['ki','き','キ','ki'],['ku','く','ク','cư'],['ke','け','ケ','kê'],['ko','こ','コ','cô']]},
{row:'Hàng S',items:[['sa','さ','サ','sa'],['shi','し','シ','shi'],['su','す','ス','sư'],['se','せ','セ','sê'],['so','そ','ソ','sô']]},
{row:'Hàng T',items:[['ta','た','タ','ta'],['chi','ち','チ','chi'],['tsu','つ','ツ','tsư'],['te','て','テ','tê'],['to','と','ト','tô']]},
{row:'Hàng N',items:[['na','な','ナ','na'],['ni','に','ニ','ni'],['nu','ぬ','ヌ','nư'],['ne','ね','ネ','nê'],['no','の','ノ','nô']]},
{row:'Hàng H',items:[['ha','は','ハ','ha'],['hi','ひ','ヒ','hi'],['fu','ふ','フ','phư nhẹ'],['he','へ','ヘ','hê'],['ho','ほ','ホ','hô']]},
{row:'Hàng M',items:[['ma','ま','マ','ma'],['mi','み','ミ','mi'],['mu','む','ム','mư'],['me','め','メ','mê'],['mo','も','モ','mô']]},
{row:'Hàng Y',items:[['ya','や','ヤ','ya'],null,['yu','ゆ','ユ','yu'],null,['yo','よ','ヨ','yô']]},
{row:'Hàng R',items:[['ra','ら','ラ','ra, r nhẹ'],['ri','り','リ','ri, r nhẹ'],['ru','る','ル','rư, r nhẹ'],['re','れ','レ','rê, r nhẹ'],['ro','ろ','ロ','rô, r nhẹ']]},
{row:'Hàng W',items:[['wa','わ','ワ','oa/wa'],null,null,null,['wo','を','ヲ','ô, trợ từ']]},
{row:'Âm cuối',items:[null,null,['n','ん','ン','n/ng nhẹ'],null,null]}
];
const VOICED_ROWS=[
{row:'Hàng G',items:[['ga','が','ガ','ga'],['gi','ぎ','ギ','ghi/gi'],['gu','ぐ','グ','gư'],['ge','げ','ゲ','ghê'],['go','ご','ゴ','gô']]},
{row:'Hàng Z',items:[['za','ざ','ザ','za'],['ji','じ','ジ','ji'],['zu','ず','ズ','zư'],['ze','ぜ','ゼ','zê'],['zo','ぞ','ゾ','zô']]},
{row:'Hàng D',items:[['da','だ','ダ','đa'],['ji2','ぢ','ヂ','ji'],['zu2','づ','ヅ','zư'],['de','で','デ','đê'],['do','ど','ド','đô']]},
{row:'Hàng B',items:[['ba','ば','バ','ba'],['bi','び','ビ','bi'],['bu','ぶ','ブ','bư'],['be','べ','ベ','bê'],['bo','ぼ','ボ','bô']]},
{row:'Hàng P',items:[['pa','ぱ','パ','pa'],['pi','ぴ','ピ','pi'],['pu','ぷ','プ','pư'],['pe','ぺ','ペ','pê'],['po','ぽ','ポ','pô']]}
];
const COMBO_ROWS=[
{row:'K',items:[['kya','きゃ','キャ','kya'],['kyu','きゅ','キュ','kyu'],['kyo','きょ','キョ','kyô']]},
{row:'G',items:[['gya','ぎゃ','ギャ','gya'],['gyu','ぎゅ','ギュ','gyu'],['gyo','ぎょ','ギョ','gyô']]},
{row:'S',items:[['sha','しゃ','シャ','sha'],['shu','しゅ','シュ','shu'],['sho','しょ','ショ','shô']]},
{row:'J',items:[['ja','じゃ','ジャ','ja'],['ju','じゅ','ジュ','ju'],['jo','じょ','ジョ','jô']]},
{row:'T',items:[['cha','ちゃ','チャ','cha'],['chu','ちゅ','チュ','chu'],['cho','ちょ','チョ','chô']]},
{row:'N',items:[['nya','にゃ','ニャ','nya'],['nyu','にゅ','ニュ','nyu'],['nyo','にょ','ニョ','nyô']]},
{row:'H',items:[['hya','ひゃ','ヒャ','hya'],['hyu','ひゅ','ヒュ','hyu'],['hyo','ひょ','ヒョ','hyô']]},
{row:'B',items:[['bya','びゃ','ビャ','bya'],['byu','びゅ','ビュ','byu'],['byo','びょ','ビョ','byô']]},
{row:'P',items:[['pya','ぴゃ','ピャ','pya'],['pyu','ぴゅ','ピュ','pyu'],['pyo','ぴょ','ピョ','pyô']]},
{row:'M',items:[['mya','みゃ','ミャ','mya'],['myu','みゅ','ミュ','myu'],['myo','みょ','ミョ','myô']]},
{row:'R',items:[['rya','りゃ','リャ','rya'],['ryu','りゅ','リュ','ryu'],['ryo','りょ','リョ','ryô']]}
];
const EXAMPLES={a:['あさ','asa','buổi sáng'],i:['いぬ','inu','con chó'],u:['うみ','umi','biển'],e:['えき','eki','nhà ga'],o:['おと','oto','âm thanh'],ka:['かさ','kasa','ô, dù'],ki:['き','ki','cây'],ku:['くち','kuchi','miệng'],ke:['けさ','kesa','sáng nay'],ko:['こえ','koe','giọng nói'],sa:['さかな','sakana','cá'],shi:['しお','shio','muối'],su:['すし','sushi','sushi'],se:['せかい','sekai','thế giới'],so:['そら','sora','bầu trời'],ta:['たまご','tamago','trứng'],chi:['ちず','chizu','bản đồ'],tsu:['つき','tsuki','mặt trăng'],te:['て','te','tay'],to:['とり','tori','chim'],na:['なつ','natsu','mùa hè'],ni:['にく','niku','thịt'],nu:['ぬの','nuno','vải'],ne:['ねこ','neko','mèo'],no:['のり','nori','rong biển'],ha:['はな','hana','hoa'],hi:['ひ','hi','lửa'],fu:['ふね','fune','thuyền'],he:['へや','heya','căn phòng'],ho:['ほし','hoshi','ngôi sao'],ma:['まど','mado','cửa sổ'],mi:['みみ','mimi','tai'],mu:['むし','mushi','côn trùng'],me:['め','me','mắt'],mo:['もり','mori','rừng'],ya:['やま','yama','núi'],yu:['ゆき','yuki','tuyết'],yo:['よる','yoru','ban đêm'],ra:['らいねん','rainen','năm sau'],ri:['りんご','ringo','táo'],ru:['くるま','kuruma','ô tô'],re:['れきし','rekishi','lịch sử'],ro:['ろく','roku','số sáu'],wa:['わたし','watashi','tôi'],wo:['みずをのむ','mizu o nomu','uống nước'],n:['ほん','hon','sách']};
const SPECIAL_TIPS={shi:'し đọc “shi”, không đọc “si” cứng như tiếng Việt.',chi:'ち đọc gần “chi”. Đầu lưỡi nhẹ, không bật quá mạnh.',tsu:'つ đọc “tsư”: bắt đầu bằng t rồi chuyển nhanh sang sư trong một nhịp.',fu:'ふ nằm giữa “fu” và “hu”. Thổi hơi nhẹ qua hai môi, không cắn môi dưới.',ra:'Hàng ら không phải r rung mạnh. Chạm đầu lưỡi rất nhanh, gần giữa r và l.',ri:'Hàng ら không phải r rung mạnh. Chạm đầu lưỡi rất nhanh, gần giữa r và l.',ru:'Hàng ら không phải r rung mạnh. Chạm đầu lưỡi rất nhanh, gần giữa r và l.',re:'Hàng ら không phải r rung mạnh. Chạm đầu lưỡi rất nhanh, gần giữa r và l.',ro:'Hàng ら không phải r rung mạnh. Chạm đầu lưỡi rất nhanh, gần giữa r và l.',wo:'を hiện nay thường đọc giống お (o), chủ yếu dùng làm trợ từ đánh dấu tân ngữ.',n:'ん thay đổi nhẹ theo âm đứng sau, có thể nghe gần n, m hoặc ng nhưng vẫn là một mora riêng.',ji2:'ぢ hiếm gặp và thường phát âm gần giống じ.',zu2:'づ hiếm gặp và thường phát âm gần giống ず.'};
const CONFUSIONS={'さ':'Dễ nhầm với き. さ có phần cong mở hơn và ít nét giao nhau hơn.','き':'Dễ nhầm với さ. Hãy chú ý hai nét ngang rõ ở phía trên.','ぬ':'Dễ nhầm với め. ぬ có vòng móc và phần đuôi kéo ra.','め':'Dễ nhầm với ぬ. め kết thúc gọn hơn, không có vòng móc ngoài.','れ':'Dễ nhầm với ね. ね có vòng tròn rõ ở phía phải.','ね':'Dễ nhầm với れ. ね có vòng tròn rõ ở phía phải.','シ':'Dễ nhầm với ツ. Hai chấm của シ xếp gần theo chiều dọc, nét dài đi lên.','ツ':'Dễ nhầm với シ. Hai chấm của ツ xếp gần theo chiều ngang, nét dài đi xuống.','ソ':'Dễ nhầm với ン. Ở ソ, nét ngắn hướng xuống; nét dài đi từ trên xuống.','ン':'Dễ nhầm với ソ. Ở ン, nét ngắn hướng ngang; nét dài đi từ dưới lên.'};
const $=id=>document.getElementById(id);
const state={view:'table',script:'hiragana',group:'basic',selected:null,cardList:[],cardIndex:0,game:null,strokes:[],drawing:false,guide:true,writeIndex:0,voice:null};
const learned=new Set(JSON.parse(localStorage.getItem('kanaLearnedV1')||'[]'));
const writeBest=JSON.parse(localStorage.getItem('kanaWriteScoresV1')||'{}');
function toItem(raw,group='basic'){if(!raw)return null;return{id:raw[0],roma:raw[0].replace(/2$/,''),h:raw[1],k:raw[2],vi:raw[3],group}}
function flattenRows(rows,group){return rows.flatMap(r=>r.items.filter(Boolean).map(x=>toItem(x,group)))}
const basicItems=flattenRows(BASIC_ROWS,'basic'),voicedItems=flattenRows(VOICED_ROWS,'voiced'),comboItems=flattenRows(COMBO_ROWS,'combo'),allItems=[...basicItems,...voicedItems,...comboItems];
function rowsForGroup(){return state.group==='basic'?BASIC_ROWS:state.group==='voiced'?VOICED_ROWS:COMBO_ROWS}
function itemsForGroup(group){if(group==='basic')return basicItems;if(group==='voiced')return [...basicItems,...voicedItems];if(group==='all')return allItems;return group==='combo'?comboItems:voicedItems}
function showToast(text){const t=$('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function saveLearned(){localStorage.setItem('kanaLearnedV1',JSON.stringify([...learned]));updateProgress()}
function updateProgress(){const count=basicItems.reduce((n,i)=>n+(learned.has('h:'+i.id)?1:0)+(learned.has('k:'+i.id)?1:0),0),total=basicItems.length*2,pct=Math.round(count/total*100);$('overallProgress').style.width=pct+'%';$('progressLabel').textContent=`${count}/${total} chữ`;$('progressPercent').textContent=pct+'%'}
function switchView(view){state.view=view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+view));document.querySelectorAll('.mode-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='cards')prepareCards();if(view==='game'&&!state.game)startGame();if(view==='write')setTimeout(setupCanvas,30)}
document.querySelectorAll('.mode-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function renderTable(){const combo=state.group==='combo';$('kanaHead').innerHTML=`<tr><th>Hàng</th>${(combo?['ゃ / ャ','ゅ / ュ','ょ / ョ']:['a','i','u','e','o']).map(x=>`<th>${x}</th>`).join('')}</tr>`;$('kanaBody').innerHTML=rowsForGroup().map(row=>`<tr><td>${row.row}</td>${row.items.map(raw=>{if(!raw)return'<td><div class="empty-cell"></div></td>';const i=toItem(raw,state.group),chars=state.script==='hiragana'?i.h:state.script==='katakana'?i.k:`${i.h} ${i.k}`,keys=state.script==='both'?['h:'+i.id,'k:'+i.id]:[(state.script==='hiragana'?'h:':'k:')+i.id],isLearned=keys.every(k=>learned.has(k));return`<td><button class="kana-cell ${isLearned?'learned':''}" data-id="${i.id}"><span class="char">${chars}</span><span class="roma">${i.roma}</span><span class="hint">${i.vi}</span></button></td>`}).join('')}</tr>`).join('');document.querySelectorAll('.kana-cell').forEach(b=>b.onclick=()=>selectDetail(findItem(b.dataset.id)))}
function findItem(id){return allItems.find(i=>i.id===id)}
function selectedChar(item){return state.script==='hiragana'?item.h:state.script==='katakana'?item.k:`${item.h} / ${item.k}`}
function selectDetail(item){state.selected=item;$('detailChar').textContent=selectedChar(item);$('detailRoma').textContent=item.roma;$('detailPair').textContent=`Hiragana ${item.h} · Katakana ${item.k} · Gợi âm: ${item.vi}`;const tip=SPECIAL_TIPS[item.id]||`Âm “${item.roma}” gồm phụ âm và nguyên âm. Đọc gọn trong một nhịp, không kéo dài âm cuối.`;const confusion=[CONFUSIONS[item.h],CONFUSIONS[item.k]].filter(Boolean).join(' ');$('detailTip').innerHTML=`<strong>Cách đọc:</strong> ${tip}${confusion?`<br><strong>Phân biệt:</strong> ${confusion}`:''}`;const ex=EXAMPLES[item.id];$('detailExamples').innerHTML=ex?`<div class="mini-item"><span>${ex[0]} (${ex[1]})</span><strong>${ex[2]}</strong></div><div class="mini-item"><span>Nhịp đọc</span><strong>1 mora</strong></div>`:`<div class="mini-item"><span>Loại âm</span><strong>${item.group==='combo'?'Âm ghép':item.group==='voiced'?'Biến âm':'Âm cơ bản'}</strong></div>`;updateDetailLearned()}
function currentLearnKeys(){const i=state.selected;if(!i)return[];return state.script==='both'?['h:'+i.id,'k:'+i.id]:[(state.script==='hiragana'?'h:':'k:')+i.id]}
function updateDetailLearned(){const done=currentLearnKeys().every(k=>learned.has(k));$('detailLearned').textContent=done?'✓ Đã nhớ':'✓ Đánh dấu đã nhớ'}
$('detailLearned').onclick=()=>{if(!state.selected)return;const keys=currentLearnKeys(),done=keys.every(k=>learned.has(k));keys.forEach(k=>done?learned.delete(k):learned.add(k));saveLearned();renderTable();updateDetailLearned();showToast(done?'Đã bỏ đánh dấu':'Đã lưu là đã nhớ')};
function scoreVoice(v){const n=v.name.toLowerCase();let s=0;if(/^ja/i.test(v.lang))s+=100;if(/premium|enhanced|natural|neural|siri/.test(n))s+=45;if(/kyoko|otoya|nanami|keita|aoi|daichi|mayu|naoki|shiori/.test(n))s+=30;if(v.localService)s+=8;return s}
function refreshVoice(){if(!('speechSynthesis'in window))return;const voices=speechSynthesis.getVoices().filter(v=>/^ja/i.test(v.lang)).sort((a,b)=>scoreVoice(b)-scoreVoice(a));state.voice=voices[0]||null}
function speak(item,onend){if(!item)return;if(!('speechSynthesis'in window)){onend?.();return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(item.h);u.lang='ja-JP';u.rate=.72;u.pitch=.94;u.volume=.82;if(state.voice)u.voice=state.voice;u.onend=()=>onend?.();u.onerror=()=>onend?.();speechSynthesis.speak(u)}
refreshVoice();if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=refreshVoice;
$('detailSpeak').onclick=()=>speak(state.selected);$('writeSpeak').onclick=()=>speak(allItems[state.writeIndex]);
document.querySelectorAll('#scriptChips .chip').forEach(c=>c.onclick=()=>{state.script=c.dataset.script;document.querySelectorAll('#scriptChips .chip').forEach(x=>x.classList.toggle('active',x===c));renderTable();if(state.selected)selectDetail(state.selected)});
$('groupSelect').onchange=e=>{state.group=e.target.value;renderTable();selectDetail((state.group==='basic'?basicItems:state.group==='voiced'?voicedItems:comboItems)[0])};
let rowPlaying=false;$('playRowBtn').onclick=()=>{if(rowPlaying){speechSynthesis?.cancel();rowPlaying=false;$('playRowBtn').textContent='▶ Đọc lần lượt';return}const list=(state.group==='basic'?basicItems:state.group==='voiced'?voicedItems:comboItems),btn=$('playRowBtn');rowPlaying=true;btn.textContent='■ Dừng đọc';let i=0;const next=()=>{if(!rowPlaying||i>=list.length){rowPlaying=false;btn.textContent='▶ Đọc lần lượt';return}selectDetail(list[i]);speak(list[i++],()=>setTimeout(next,180))};next()};
$('resetLearnedBtn').onclick=()=>{if(confirm('Xóa toàn bộ dấu “đã nhớ” của bảng chữ cái?')){learned.clear();saveLearned();renderTable();updateDetailLearned()}};
function cardPool(){const pool=$('cardGroup').value==='basic'?basicItems:allItems,script=$('cardScript').value;return pool.map(i=>({item:i,script:script==='mixed'?(Math.random()<.5?'hiragana':'katakana'):script}))}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function prepareCards(){state.cardList=shuffle(cardPool());state.cardIndex=0;renderCard()}
function renderCard(){if(!state.cardList.length)prepareCards();const c=state.cardList[state.cardIndex%state.cardList.length];$('studyChar').textContent=c.script==='hiragana'?c.item.h:c.item.k;$('studyAnswer').hidden=true;$('studyAnswer').innerHTML=`<strong>${c.item.roma}</strong><p>Gợi âm tiếng Việt: ${c.item.vi}</p>`;$('revealAnswer').textContent='Hiện đáp án'}
$('revealAnswer').onclick=()=>{const a=$('studyAnswer');a.hidden=!a.hidden;$('revealAnswer').textContent=a.hidden?'Hiện đáp án':'Ẩn đáp án'};$('nextStudy').onclick=()=>{state.cardIndex=(state.cardIndex+1)%state.cardList.length;renderCard()};$('shuffleCardBtn').onclick=prepareCards;$('cardScript').onchange=prepareCards;$('cardGroup').onchange=prepareCards;$('studySpeak').onclick=()=>speak(state.cardList[state.cardIndex]?.item);
function labelFor(item,type,scriptMode){if(type==='h')return item.h;if(type==='k')return item.k;if(type==='roma')return item.roma;if(type==='vi')return item.vi;if(type==='sound')return'🔊 Nghe âm';if(type==='kana'){const s=scriptMode==='mixed'?(Math.random()<.5?'hiragana':'katakana'):scriptMode;return s==='hiragana'?item.h:item.k}return item.h}
function startGame(){const mode=$('gameMode').value,count=+$('pairCount').value,group=$('gameGroup').value,script=$('gameScript').value,pool=shuffle(itemsForGroup(group)).slice(0,count);let lt='h',rt='k';if(mode==='kana-romaji'){lt='kana';rt='roma'}if(mode==='kana-vi'){lt='kana';rt='vi'}if(mode==='sound-kana'){lt='sound';rt='kana'}state.game={mode,pairs:pool.map(i=>i.id),left:shuffle(pool.map(i=>({item:i,type:lt}))),right:shuffle(pool.map(i=>({item:i,type:rt}))),selectedL:null,selectedR:null,matched:new Set(),score:0,correct:0,mistakes:0,streak:0,lastSound:null,script};renderGame()}
function gameCard(side,entry,index){const matched=state.game.matched.has(entry.item.id),label=labelFor(entry.item,entry.type,state.game.script),sound=entry.type==='sound';return`<button class="match-card ${matched?'matched':''}" data-side="${side}" data-index="${index}" ${matched?'disabled':''}>${sound?`<span class="sound-card"><span class="sound-icon">🔊</span><span class="small">Nghe rồi chọn chữ</span></span>`:`<span class="${['h','k','kana'].includes(entry.type)?'large':'small'}">${label}</span>`}</button>`}
function renderGame(){const g=state.game;$('leftBoard').innerHTML=g.left.map((e,i)=>gameCard('L',e,i)).join('');$('rightBoard').innerHTML=g.right.map((e,i)=>gameCard('R',e,i)).join('');$('gameScore').textContent=g.score;$('gameCorrect').textContent=g.correct;$('gameMistakes').textContent=g.mistakes;$('gameStreak').textContent=g.streak;document.querySelectorAll('.match-card').forEach(b=>b.onclick=()=>selectGameCard(b))}
function selectGameCard(btn){const g=state.game,side=btn.dataset.side,index=+btn.dataset.index,entry=(side==='L'?g.left:g.right)[index];if(entry.type==='sound'){g.lastSound=entry.item;speak(entry.item)}document.querySelectorAll(`.match-card[data-side="${side}"]`).forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');if(side==='L')g.selectedL={index,entry,btn};else g.selectedR={index,entry,btn};if(g.selectedL&&g.selectedR)checkMatch()}
function checkMatch(){const g=state.game,a=g.selectedL,b=g.selectedR;if(a.entry.item.id===b.entry.item.id){g.matched.add(a.entry.item.id);g.correct++;g.streak++;g.score+=100+Math.min(50,g.streak*10);$('gameMessage').textContent=`Đúng: ${a.entry.item.h} / ${a.entry.item.k} = ${a.entry.item.roma}.`;g.selectedL=g.selectedR=null;setTimeout(()=>{renderGame();if(g.matched.size===g.pairs.length){$('gameMessage').textContent=`Hoàn thành! Bạn ghép đúng ${g.correct} cặp với ${g.mistakes} lần nhầm.`;showToast('Hoàn thành ván chơi ✨')}},220)}else{g.mistakes++;g.streak=0;g.score=Math.max(0,g.score-15);a.btn.classList.add('wrong');b.btn.classList.add('wrong');$('gameMessage').textContent='Chưa đúng. Nghe hoặc nhìn lại rồi thử một cặp khác.';setTimeout(()=>{a.btn.classList.remove('wrong','selected');b.btn.classList.remove('wrong','selected');g.selectedL=g.selectedR=null;renderGame()},360)}}
$('newGameBtn').onclick=startGame;['gameMode','gameScript','pairCount','gameGroup'].forEach(id=>$(id).onchange=startGame);$('replayGameBtn').onclick=()=>{if(state.game?.lastSound)speak(state.game.lastSound);else showToast('Chưa có âm nào được chọn')};
const canvas=$('drawCanvas'),wrap=$('canvasWrap'),ctx=canvas.getContext('2d');
function setupCanvas(){const rect=wrap.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);canvas.style.width=rect.width+'px';canvas.style.height=rect.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#5f48d2';ctx.lineWidth=Math.max(9,rect.width*.032);redrawStrokes();populateWriteSelect();renderWriteTarget()}
function populateWriteSelect(){if($('writeCharSelect').options.length)return;$('writeCharSelect').innerHTML=allItems.map((i,idx)=>`<option value="${idx}">${i.h} / ${i.k} · ${i.roma}</option>`).join('')}
function pointFromEvent(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);state.drawing=true;state.strokes.push([pointFromEvent(e)]);redrawStrokes()});canvas.addEventListener('pointermove',e=>{if(!state.drawing)return;e.preventDefault();state.strokes[state.strokes.length-1].push(pointFromEvent(e));redrawStrokes()});['pointerup','pointercancel'].forEach(type=>canvas.addEventListener(type,e=>{state.drawing=false;try{canvas.releasePointerCapture(e.pointerId)}catch{}}));
function redrawStrokes(){const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);ctx.strokeStyle='#5f48d2';ctx.lineWidth=Math.max(9,r.width*.032);state.strokes.forEach(st=>{if(!st.length)return;ctx.beginPath();ctx.moveTo(st[0].x,st[0].y);if(st.length===1)ctx.lineTo(st[0].x+.1,st[0].y+.1);else st.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke()})}
function clearWriting(){state.strokes=[];redrawStrokes();$('writeScore').textContent='--';$('scoreRing').style.setProperty('--score','0%');$('scoreTitle').textContent='Chưa chấm điểm';$('scoreFeedback').textContent='Viết chữ theo mẫu, cố gắng đi giữa nét mờ và phủ đủ toàn bộ hình chữ.'}
function currentWriteItem(){return allItems[state.writeIndex]}
function renderWriteTarget(){const i=currentWriteItem(),script=$('writeScript').value,char=script==='hiragana'?i.h:i.k;$('guideChar').textContent=char;$('writeTargetChar').textContent=char;$('writeTargetRoma').textContent=i.roma;const best=writeBest[script+':'+i.id];$('writeTargetHint').textContent=`Gợi âm: ${i.vi}${best!=null?` · Điểm tốt nhất: ${best}`:''}`;$('writeCharSelect').value=state.writeIndex;clearWriting()}
$('writeCharSelect').onchange=e=>{state.writeIndex=+e.target.value;renderWriteTarget()};$('writeScript').onchange=renderWriteTarget;$('prevWrite').onclick=()=>{state.writeIndex=(state.writeIndex-1+allItems.length)%allItems.length;renderWriteTarget()};$('nextWrite').onclick=()=>{state.writeIndex=(state.writeIndex+1)%allItems.length;renderWriteTarget()};$('undoStroke').onclick=()=>{state.strokes.pop();redrawStrokes()};$('clearCanvas').onclick=clearWriting;$('toggleGuide').onclick=()=>{state.guide=!state.guide;$('guideChar').style.display=state.guide?'grid':'none';$('toggleGuide').textContent=state.guide?'Ẩn chữ mẫu':'Hiện chữ mẫu'};
function drawMaskFromStrokes(size=320){const c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d');const r=canvas.getBoundingClientRect(),sx=size/r.width,sy=size/r.height;x.strokeStyle='#000';x.lineCap='round';x.lineJoin='round';x.lineWidth=size*.034;state.strokes.forEach(st=>{if(!st.length)return;x.beginPath();x.moveTo(st[0].x*sx,st[0].y*sy);st.slice(1).forEach(p=>x.lineTo(p.x*sx,p.y*sy));x.stroke()});return x.getImageData(0,0,size,size).data}
function drawGlyphMask(char,size=320){const c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d');x.fillStyle='#000';x.textAlign='center';x.textBaseline='middle';x.font=`850 ${size*.72}px "Hiragino Kaku Gothic ProN","Yu Gothic",sans-serif`;x.fillText(char,size/2,size*.52);return x.getImageData(0,0,size,size).data}
function binary(data){const out=new Uint8Array(data.length/4);for(let i=0,j=3;j<data.length;i++,j+=4)out[i]=data[j]>30?1:0;return out}
function dilate(src,size,radius){const out=new Uint8Array(src.length);for(let y=0;y<size;y++)for(let x=0;x<size;x++){if(!src[y*size+x])continue;for(let dy=-radius;dy<=radius;dy++)for(let dx=-radius;dx<=radius;dx++){if(dx*dx+dy*dy>radius*radius)continue;const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<size&&ny<size)out[ny*size+nx]=1}}return out}
function writingScore(){if(state.strokes.length===0){showToast('Hãy viết chữ trước khi chấm');return}const size=260,i=currentWriteItem(),script=$('writeScript').value,char=script==='hiragana'?i.h:i.k,user=binary(drawMaskFromStrokes(size)),glyph=binary(drawGlyphMask(char,size)),wideGlyph=dilate(glyph,size,9),wideUser=dilate(user,size,8);let userN=0,glyphN=0,userOn=0,glyphOn=0;for(let p=0;p<user.length;p++){if(user[p]){userN++;if(wideGlyph[p])userOn++}if(glyph[p]){glyphN++;if(wideUser[p])glyphOn++}}const precision=userN?userOn/userN:0,coverage=glyphN?glyphOn/glyphN:0;let score=Math.round((precision*.55+coverage*.45)*100);if(userN<glyphN*.22)score=Math.min(score,48);score=Math.max(0,Math.min(100,score));$('writeScore').textContent=score;$('scoreRing').style.setProperty('--score',score+'%');let title,feedback;if(score>=90){title='Rất giống chữ mẫu';feedback='Nét viết bám tốt và phủ khá đầy đủ. Tiếp theo hãy ẩn chữ mẫu rồi viết lại.'}else if(score>=80){title='Viết tốt';feedback='Hình chữ đã rõ. Hãy sửa những đoạn nét đi lệch khỏi vùng mẫu.'}else if(score>=70){title='Đạt mục tiêu ban đầu';feedback='Bạn đã nắm được hình chữ. Viết chậm hơn để nét đi giữa phần chữ mờ.'}else if(score>=55){title='Cần luyện thêm';feedback='Một số nét còn thiếu hoặc lệch. Bật chữ mẫu, viết từng nét chậm và phủ đủ hơn.'}else{title='Thử lại từ đầu';feedback='Hình viết chưa gần chữ mẫu. Hãy xóa, quan sát tỷ lệ và viết từng phần nhỏ.'}$('scoreTitle').textContent=title;$('scoreFeedback').textContent=`${feedback} Độ bám nét ${Math.round(precision*100)}%, độ phủ ${Math.round(coverage*100)}%.`;const key=script+':'+i.id;if(writeBest[key]==null||score>writeBest[key]){writeBest[key]=score;localStorage.setItem('kanaWriteScoresV1',JSON.stringify(writeBest));renderWriteTargetInfo(i,script)}}
function renderWriteTargetInfo(i,script){$('writeTargetHint').textContent=`Gợi âm: ${i.vi} · Điểm tốt nhất: ${writeBest[script+':'+i.id]}`}
$('scoreWriting').onclick=writingScore;window.addEventListener('resize',()=>{if(state.view==='write')setupCanvas()});
state.selected=basicItems[0];renderTable();selectDetail(state.selected);updateProgress();prepareCards();populateWriteSelect();renderWriteTarget();
