(()=>{try{localStorage.removeItem('fc_offline_recent_lessons_v1');if('serviceWorker'in navigator)navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).catch(()=>{});if('caches'in window)caches.keys().then(keys=>keys.filter(k=>k.startsWith('duan-flashcard')).forEach(k=>caches.delete(k))).catch(()=>{})}catch{}})();
const q=s=>document.querySelector(s),S={p:'fc_vocab_progress_v2',l:'fc_vocab_last_v2',r:'fc_vocab_show_reading_v2',t:'fc_vocab_theme_v2'};
const st={lessons:[],lesson:null,cards:[],session:[],i:0,face:0,filter:'all',known:new Set(),again:new Set(),showReading:false,done:false};window.st=st;
const e={theme:q('#themeToggle'),list:q('#lessonList'),meta:q('#lessonMeta'),from:q('#fromInput'),to:q('#toInput'),limit:q('#limitSelect'),shuffle:q('#shuffleInput'),start:q('#startBtn'),review:q('#reviewBtn'),reset:q('#resetBtn'),title:q('#sessionTitle'),pos:q('#posText'),known:q('#knownText'),again:q('#againText'),bar:q('#progressBar'),card:q('#card'),front:q('#cardFront'),sub:q('#cardSub'),hint:q('#cardHint'),actions:q('#actions'),prev:q('#prevBtn'),next:q('#nextBtn'),flip:q('#flipBtn'),bad:q('#againBtn'),ok:q('#knownBtn'),log:q('#logBox')};window.e=e;
let logs=[];function d(x){logs.unshift(new Date().toLocaleTimeString()+' · '+x);logs=logs.slice(0,80);const p=q('#debugPaneText');if(p)p.textContent=logs.join('\n')}function log(x){d(x);if(e.log)e.log.textContent=new Date().toLocaleTimeString()+' · '+x+'\n'+e.log.textContent}
function debugUI(){if(q('#debugBtn'))return;let s=document.createElement('style');s.textContent='#debugBtn{position:fixed;right:14px;bottom:14px;z-index:99999;border:0;border-radius:999px;background:#111827;color:white;padding:10px 14px;font-weight:800;box-shadow:0 12px 30px #0004}#debugPane{display:none;position:fixed;left:10px;right:10px;bottom:62px;z-index:99998;max-height:45vh;overflow:auto;background:#0f172af2;color:#e5e7eb;border-radius:16px;padding:12px;font:12px/1.5 ui-monospace,Menlo,monospace;white-space:pre-wrap}#debugPane.on{display:block}';document.head.appendChild(s);let b=document.createElement('button');b.id='debugBtn';b.textContent='Log';let p=document.createElement('div');p.id='debugPane';p.innerHTML='<b>Debug Log</b><pre id="debugPaneText"></pre>';document.body.append(b,p);b.onclick=()=>{p.classList.toggle('on');q('#debugPaneText').textContent=logs.join('\n')}}
window.onerror=(m,s,l)=>d('JS ERROR: '+m+' @'+l);window.onunhandledrejection=ev=>d('PROMISE: '+(ev.reason?.message||ev.reason));debugUI();d('app boot: stable features');
const fallback={courses:[{title:'400 từ vựng N2 - Trường văn',lessons:[1,51,101,151,201,251,301,351].map((n,i)=>({id:`n2-reading-${String(n).padStart(3,'0')}-${String(n+49).padStart(3,'0')}`,title:`Bài ${String(i+1).padStart(2,'0')} · STT ${n}-${n+49}`,path:`./data/n2-reading-${String(n).padStart(3,'0')}-${String(n+49).padStart(3,'0')}.tsv`,count:50,startNo:n,endNo:n+49}))}]};
async function getText(url){d('fetch '+url);let r=await fetch(url,{cache:'reload'});d('status '+r.status+' '+url);if(!r.ok)throw Error(r.status+' '+url);return await r.text()}
function theme(){try{let dark=localStorage.getItem(S.t)==='dark';document.documentElement.classList.toggle('dark',dark)}catch{}}function toggleTheme(){let d=document.documentElement.classList.toggle('dark');try{localStorage.setItem(S.t,d?'dark':'light')}catch{}}
function buildLibraryUi(){const panel=q('.library-panel'),title=panel?.querySelector('.title-row');if(!panel||q('.library-tabs'))return;let tabs=document.createElement('div');tabs.className='library-tabs';tabs.innerHTML='<button class="library-tab active" type="button" data-tab="vocab">Từ vựng</button><button class="library-tab" type="button" data-tab="grammar">Ngữ pháp</button><button class="library-tab" type="button" data-tab="kanji">Kanji</button>';let sum=document.createElement('p');sum.className='library-summary';sum.textContent='400 từ vựng N2. Chọn bài rồi học theo block 10 từ.';title.after(tabs,sum);tabs.onclick=ev=>{let b=ev.target.closest('button');if(!b)return;tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.tab==='vocab'){e.list.style.display='grid';sum.textContent='400 từ vựng N2. Chọn bài rồi học theo block 10 từ.'}else{e.list.style.display='none';sum.textContent=(b.dataset.tab==='grammar'?'Ngữ pháp':'Kanji')+' đã chuẩn bị data, sẽ bật sau khi import file.';log('Tab '+b.textContent+' chưa bật data.') }} }
function buildSwitches(){try{st.showReading=localStorage.getItem(S.r)==='on'}catch{};let old=e.shuffle.closest('label');old?.classList.add('hidden-native-switch');let row=q('#studySwitches');if(!row){row=document.createElement('div');row.id='studySwitches';row.className='study-switches';row.innerHTML='<label class="ios-switch"><span>Shuffle</span><input id="shuffleSwitch" type="checkbox"><span class="switch-track"></span></label><label class="ios-switch"><span>Reading</span><input id="readingSwitch" type="checkbox"><span class="switch-track"></span></label>';q('.study-head')?.after(row)}let sw=q('#shuffleSwitch'),rd=q('#readingSwitch');sw.checked=e.shuffle.checked;rd.checked=st.showReading;sw.onchange=()=>{e.shuffle.checked=sw.checked;saveLast()};rd.onchange=()=>{st.showReading=rd.checked;try{localStorage.setItem(S.r,st.showReading?'on':'off')}catch{};render()}}
async function loadManifest(){let m;try{m=JSON.parse(await getText('./data/manifest.json?v='+Date.now()));log('Manifest OK')}catch(err){d('manifest fallback: '+err.message);m=fallback;log('Manifest lỗi, dùng fallback.')}st.lessons=(m.courses||[]).flatMap(c=>(c.lessons||[]).map(l=>({...l,courseTitle:c.title})));renderMenu();log('Có '+st.lessons.length+' bài')}
function renderMenu(){e.list.innerHTML='';st.lessons.forEach((l,i)=>{let b=document.createElement('button');b.type='button';b.className='lesson-btn';b.innerHTML='<strong>'+l.title+'</strong><span>'+(l.courseTitle||'')+' · '+l.count+' thẻ</span>';b.onclick=()=>selectLesson(l.id);e.list.appendChild(b);if(i===0&&!st.lesson)setTimeout(()=>selectLesson(l.id),0)})}
async function selectLesson(id){let l=st.lessons.find(x=>x.id===id);if(!l)return;try{st.lesson=l;document.querySelectorAll('.lesson-btn').forEach((b,i)=>b.classList.toggle('active',st.lessons[i]?.id===id));let txt=await getText(l.path+'?v='+Date.now());st.cards=parseTSV(txt).map((c,i)=>({...c,no:i+1,id:l.id+'-'+(i+1)}));e.from.value=1;e.to.value=st.cards.length;e.meta.textContent=l.title+' · '+st.cards.length+' thẻ';st.session=[];st.i=0;st.face=0;st.filter='all';loadProgress();saveLast();render();log('Đã chọn '+l.title)}catch(err){d('lesson error '+err.message);e.title.textContent='Lỗi tải bài';e.front.textContent='Không tải được data';e.sub.textContent=err.message;e.hint.textContent='Bấm Log dưới cùng để xem lỗi.';log('Lỗi tải bài: '+err.message)}}
function parseTSV(t){let lines=t.trim().split(/\r?\n/).filter(Boolean),h=lines.shift().split('\t');return lines.map(line=>{let v=line.split('\t'),o={};h.forEach((k,i)=>o[k]=v[i]||'');return{front:o.front,reading:o.reading,meaning_vi:o.meaning_vi,han_viet:o.han_viet,years:o.years}})}
function loadProgress(){try{let all=JSON.parse(localStorage.getItem(S.p)||'{}'),p=all[st.lesson?.id]||{known:[],again:[]};st.known=new Set(p.known);st.again=new Set(p.again)}catch{}stats()}function saveProgress(){try{let all=JSON.parse(localStorage.getItem(S.p)||'{}');all[st.lesson.id]={known:[...st.known],again:[...st.again]};localStorage.setItem(S.p,JSON.stringify(all))}catch{}}function saveLast(){try{localStorage.setItem(S.l,JSON.stringify({lessonId:st.lesson?.id,from:e.from.value,to:e.to.value,limit:e.limit.value,shuffle:e.shuffle.checked}))}catch{}}
function baseCards(){let a=Math.max(1,+e.from.value||1),b=Math.min(st.cards.length,+e.to.value||st.cards.length);if(a>b)[a,b]=[b,a];let arr=st.cards.filter(c=>c.no>=a&&c.no<=b);if(e.limit.value!=='all')arr=arr.slice(0,+e.limit.value);if(e.shuffle.checked)arr=[...arr].sort(()=>Math.random()-.5);return arr}function filteredCards(mode=st.filter){let arr=baseCards();if(mode==='known')arr=arr.filter(c=>st.known.has(c.id));if(mode==='again')arr=arr.filter(c=>st.again.has(c.id));return arr}function current(){return st.session[st.i]}function meta(x){let m=q('#cardMeta');if(m)m.textContent=x||''}
function start(){if(!st.cards.length)return log('Chưa có card.');st.filter='all';st.session=filteredCards('all');st.i=0;st.face=0;render();saveLast();log('Bắt đầu học '+st.session.length+' thẻ.')}
function applyFilter(mode){if(!st.cards.length)return;st.filter=mode;st.session=filteredCards(mode);st.i=0;st.face=0;render();log('Filter: '+(mode==='all'?'All':mode==='known'?'Biết':'Chưa nhớ')+' · '+st.session.length+' thẻ')}
function render(){let c=current();e.card.classList.remove('status-known','status-again');if(!c){e.title.textContent=st.lesson?'Chọn range rồi bấm Bắt đầu học':'Chọn bài học';e.front.textContent=st.lesson?'Sẵn sàng':'Chưa có bài';e.sub.textContent=st.lesson?st.cards.length+' thẻ trong bài này.':'Đang tải data từ GitHub...';e.hint.textContent=st.lesson?'Chọn số lượng rồi bấm Bắt đầu học.':'Đang tải menu bài học.';e.actions.classList.add('hidden');meta('');stats();return}if(st.known.has(c.id))e.card.classList.add('status-known');if(st.again.has(c.id))e.card.classList.add('status-again');e.actions.classList.remove('hidden');e.title.textContent=st.lesson.title;if(st.face===0){e.front.textContent=c.front;e.sub.textContent=st.showReading?c.reading:'';e.hint.textContent=st.showReading?'Mặt 1/2: từ + cách đọc.':'Mặt 1/2: từ.';meta('#n2')}else{e.front.textContent=c.meaning_vi;e.sub.textContent=[c.reading?'Cách đọc: '+c.reading:'',c.han_viet?'Âm Hán Việt: '+c.han_viet:''].filter(Boolean).join('\n');e.hint.textContent='Mặt 2/2: nghĩa + cách đọc.';meta(c.years?'Năm: '+c.years:'#n2')}stats()}
function stats(){let base=st.cards.length?baseCards():[],kc=base.filter(c=>st.known.has(c.id)).length,ac=base.filter(c=>st.again.has(c.id)).length;e.pos.textContent=st.session.length?(st.i+1)+'/'+st.session.length:'All: '+base.length;e.known.textContent='Biết: '+kc;e.again.textContent='Chưa nhớ: '+ac;e.bar.style.width=(st.session.length?(st.i+1)/st.session.length*100:0)+'%';e.pos.classList.toggle('status-active',st.filter==='all');e.known.classList.toggle('status-active',st.filter==='known');e.again.classList.toggle('status-active',st.filter==='again')}
function flip(){if(current()){st.face=(st.face+1)%2;render()}}function next(){if(!st.session.length)return;if(st.i>=st.session.length-1){log('Hết phiên học.');return}st.i++;st.face=0;render()}function prev(){if(st.session.length){st.i=Math.max(0,st.i-1);st.face=0;render()}}function mark(t){let c=current();if(!c)return;if(t==='known'){st.known.add(c.id);st.again.delete(c.id)}else{st.again.add(c.id);st.known.delete(c.id)}saveProgress();next()}function review(){applyFilter('again')}function reset(){if(!st.lesson||!confirm('Reset tiến độ bài này?'))return;st.known.clear();st.again.clear();saveProgress();stats();render();log('Đã reset.')}
function bind(){e.theme.onclick=toggleTheme;e.start.onclick=start;e.review.onclick=review;e.reset.onclick=reset;e.card.onclick=flip;e.flip.onclick=flip;e.prev.onclick=prev;e.next.onclick=next;e.bad.onclick=()=>mark('again');e.ok.onclick=()=>mark('known');e.pos.onclick=()=>applyFilter('all');e.known.onclick=()=>applyFilter('known');e.again.onclick=()=>applyFilter('again');[e.from,e.to,e.limit,e.shuffle].forEach(n=>n.onchange=()=>{saveLast();if(st.session.length)applyFilter(st.filter)})}
(async()=>{try{theme();buildLibraryUi();buildSwitches();bind();await loadManifest();render();d('boot done')}catch(err){d('FATAL '+err.message);e.title.textContent='Lỗi JS';e.front.textContent='App lỗi';e.sub.textContent=err.message;e.hint.textContent='Bấm Log dưới cùng.'}})();
