const S={p:'fc_vocab_progress_v2',t:'fc_vocab_theme_v2',l:'fc_vocab_last_v2',r:'fc_vocab_show_reading_v2'};
const q=s=>document.querySelector(s);
const st={manifest:null,lessons:[],lesson:null,cards:[],session:[],i:0,face:0,known:new Set(),again:new Set(),showReading:false,done:false};
const e={theme:q('#themeToggle'),list:q('#lessonList'),meta:q('#lessonMeta'),from:q('#fromInput'),to:q('#toInput'),limit:q('#limitSelect'),shuffle:q('#shuffleInput'),start:q('#startBtn'),review:q('#reviewBtn'),reset:q('#resetBtn'),title:q('#sessionTitle'),pos:q('#posText'),known:q('#knownText'),again:q('#againText'),bar:q('#progressBar'),card:q('#card'),front:q('#cardFront'),sub:q('#cardSub'),hint:q('#cardHint'),actions:q('#actions'),prev:q('#prevBtn'),next:q('#nextBtn'),flip:q('#flipBtn'),bad:q('#againBtn'),ok:q('#knownBtn'),log:q('#logBox')};
function log(x){if(e.log)e.log.textContent=`${new Date().toLocaleTimeString()} · ${x}\n`+e.log.textContent}
function metaEl(){let m=q('#cardMeta');if(!m){m=document.createElement('p');m.id='cardMeta';m.className='card-meta';e.hint?.after(m)}return m}
function setMeta(x){metaEl().textContent=x||''}
function theme(){const d=localStorage.getItem(S.t)==='dark'||(!localStorage.getItem(S.t)&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.classList.toggle('dark',d)}
function toggleTheme(){const d=document.documentElement.classList.toggle('dark');localStorage.setItem(S.t,d?'dark':'light')}
function installToggle(){st.showReading=localStorage.getItem(S.r)==='on';const label=document.createElement('label');label.innerHTML='<input id="showReadingInput" type="checkbox"> Hiện cách đọc ở mặt đầu';const input=label.querySelector('input');input.checked=st.showReading;e.shuffle.closest('label').after(label);input.onchange=()=>{st.showReading=input.checked;localStorage.setItem(S.r,st.showReading?'on':'off');render()}}
async function loadManifest(){const r=await fetch('./data/manifest.json?v='+Date.now(),{cache:'no-store'});st.manifest=await r.json();st.lessons=(st.manifest.courses||[]).flatMap(c=>(c.lessons||[]).map(l=>({...l,courseTitle:c.title})));renderLessonMenu();log(`Đã tải ${st.lessons.length} bài từ vựng.`)}
function renderLessonMenu(){e.list.innerHTML='';st.lessons.forEach((l,idx)=>{const b=document.createElement('button');b.type='button';b.className='lesson-btn';b.innerHTML=`<strong>${l.title}</strong><span>${l.courseTitle||''} · ${l.count} thẻ · STT ${l.startNo}-${l.endNo}</span>`;b.onclick=()=>selectLesson(l.id);e.list.appendChild(b);if(idx===0&&!st.lesson)selectLesson(l.id)})}
async function selectLesson(id){const l=st.lessons.find(x=>x.id===id);if(!l)return;st.lesson=l;document.querySelectorAll('.lesson-btn').forEach((b,i)=>b.classList.toggle('active',st.lessons[i].id===id));const r=await fetch(l.path+'?v='+Date.now(),{cache:'no-store'});const text=await r.text();st.cards=parseTSV(text).map((c,i)=>({...c,no:i+1,id:`${l.id}-${i+1}`}));e.from.value='1';e.to.value=String(st.cards.length);e.meta.textContent=`${l.title} · ${st.cards.length} thẻ`;st.session=[];st.i=0;st.face=0;st.done=false;loadProgress();saveLast();render();log(`Đã chọn ${l.title}.`)}
function parseTSV(text){const lines=text.trim().split(/\r?\n/).filter(Boolean);const h=lines.shift().split('\t');return lines.map(line=>{const v=line.split('\t');const o={};h.forEach((k,i)=>o[k]=v[i]||'');return{sourceNo:Number(o.no),front:o.front,reading:o.reading,meaning_vi:o.meaning_vi,han_viet:o.han_viet,years:o.years,tags:['n2','reading']}})}
function loadProgress(){const all=JSON.parse(localStorage.getItem(S.p)||'{}');const p=all[st.lesson?.id]||{known:[],again:[]};st.known=new Set(p.known);st.again=new Set(p.again);stats()}
function saveProgress(){const all=JSON.parse(localStorage.getItem(S.p)||'{}');all[st.lesson.id]={known:[...st.known],again:[...st.again]};localStorage.setItem(S.p,JSON.stringify(all))}
function saveLast(){localStorage.setItem(S.l,JSON.stringify({lessonId:st.lesson?.id,from:e.from.value,to:e.to.value,limit:e.limit.value,shuffle:e.shuffle.checked}))}
function restoreLast(){try{const x=JSON.parse(localStorage.getItem(S.l)||'{}');if(x.from)e.from.value=x.from;if(x.to)e.to.value=x.to;if(x.limit)e.limit.value=x.limit;if(typeof x.shuffle==='boolean')e.shuffle.checked=x.shuffle;if(x.lessonId)setTimeout(()=>selectLesson(x.lessonId),80)}catch{}}
function buildSession(){let a=Math.max(1,+e.from.value||1),b=Math.min(st.cards.length,+e.to.value||st.cards.length);if(a>b)[a,b]=[b,a];let arr=st.cards.filter(c=>c.no>=a&&c.no<=b);if(e.limit.value!=='all')arr=arr.slice(0,+e.limit.value);if(e.shuffle.checked)arr=shuffle(arr);return arr}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function start(){if(!st.cards.length)return;st.session=buildSession();st.i=0;st.face=0;st.done=false;document.querySelector('.complete-panel')?.remove();saveLast();render();log(`Bắt đầu học ${st.session.length} thẻ.`)}
function current(){return st.session[st.i]}
function render(){const c=current();if(!c){e.title.textContent=st.lesson?'Chọn range rồi bấm Bắt đầu học':'Chọn bài học';e.front.textContent=st.lesson?'Sẵn sàng':'Chưa có bài';e.sub.textContent=st.lesson?`${st.cards.length} thẻ trong bài này. Học 10 từ/lần hoặc chọn range.`:'Đang tải data từ GitHub.';e.hint.textContent='Bấm bài học bên trái, chọn số lượng, rồi bắt đầu.';setMeta('');e.actions.classList.add('hidden');stats();return}e.actions.classList.remove('hidden');e.title.textContent=st.lesson.title;e.pos.textContent=`${st.i+1}/${st.session.length}`;if(st.face===0){e.front.textContent=c.front;e.sub.textContent=st.showReading?c.reading:'';e.hint.textContent=st.showReading?'Mặt 1/2: từ + cách đọc.':'Mặt 1/2: từ. Cách đọc đang ẩn.';setMeta('#n2 #reading')}else{e.front.textContent=c.meaning_vi;e.sub.textContent=[c.reading?`Cách đọc: ${c.reading}`:'',c.han_viet?`Âm Hán Việt: ${c.han_viet}`:''].filter(Boolean).join('\n');e.hint.textContent='Mặt 2/2: nghĩa + cách đọc.';setMeta(c.years?`Năm xuất hiện: ${c.years}`:'#n2 #reading')}stats()}
function stats(){e.pos.textContent=st.session.length?`${st.i+1}/${st.session.length}`:'0/0';e.known.textContent=`Biết: ${st.known.size}`;e.again.textContent=`Chưa nhớ: ${st.again.size}`;e.bar.style.width=(st.session.length?(st.i+1)/st.session.length*100:0)+'%'}
function flip(){if(!current())return;st.face=(st.face+1)%2;render()}
function prev(){if(!st.session.length)return;st.i=Math.max(0,st.i-1);st.face=0;render()}
function next(){if(!st.session.length)return;if(st.i>=st.session.length-1)return complete();st.i++;st.face=0;render()}
function mark(type){const c=current();if(!c)return;if(type==='known'){st.known.add(c.id);st.again.delete(c.id)}else{st.again.add(c.id);st.known.delete(c.id)}saveProgress();type==='known'?log('Đánh dấu biết rồi.'):log('Đánh dấu chưa nhớ.');next()}
function review(){st.session=st.cards.filter(c=>st.again.has(c.id));st.i=0;st.face=0;st.done=false;render();log(`Ôn ${st.session.length} thẻ chưa nhớ.`)}
function reset(){if(!st.lesson||!confirm('Reset tiến độ bài này?'))return;st.known.clear();st.again.clear();saveProgress();stats();log('Đã reset tiến độ.')}
function fireworks(){const layer=document.createElement('div');layer.className='firework-layer';document.body.appendChild(layer);for(let b=0;b<5;b++){const cx=20+Math.random()*60,cy=18+Math.random()*44;for(let i=0;i<28;i++){const d=document.createElement('span'),ang=Math.PI*2*i/28,dist=60+Math.random()*92;d.className='firework-dot';d.style.setProperty('--x',cx+'vw');d.style.setProperty('--y',cy+'vh');d.style.setProperty('--dx',Math.cos(ang)*dist+'px');d.style.setProperty('--dy',Math.sin(ang)*dist+'px');d.style.setProperty('--hue',String(Math.floor(Math.random()*360)));d.style.animationDelay=(b*.12)+'s';layer.appendChild(d)}}setTimeout(()=>layer.remove(),2400)}
function complete(){if(st.done)return;st.done=true;fireworks();document.querySelector('.complete-panel')?.remove();const p=document.createElement('div');p.className='complete-panel';p.innerHTML='<strong>🎉 Xong phiên học!</strong><p>Đã học hết flashcard trong phiên này.</p><button type="button">Học lại từ đầu</button>';document.body.appendChild(p);p.querySelector('button').onclick=()=>{p.remove();st.i=0;st.face=0;st.done=false;render()};log('Hết phiên học. Bấm Học lại từ đầu để quay về thẻ 1.')}
function bind(){e.theme.onclick=toggleTheme;e.start.onclick=start;e.review.onclick=review;e.reset.onclick=reset;e.card.onclick=flip;e.flip.onclick=flip;e.prev.onclick=prev;e.next.onclick=next;e.bad.onclick=()=>mark('again');e.ok.onclick=()=>mark('known');[e.from,e.to,e.limit,e.shuffle].forEach(n=>n.onchange=saveLast);document.addEventListener('keydown',x=>{if(x.target.matches('input,select,textarea'))return;if(x.code==='Space'){x.preventDefault();flip()}if(x.key==='ArrowRight')next();if(x.key==='ArrowLeft')prev();if(x.key.toLowerCase()==='k')mark('known');if(x.key.toLowerCase()==='a')mark('again')})}
(async()=>{theme();installToggle();bind();await loadManifest();restoreLast();render()})();
